baseURL = 'https://lithiumm.netlify.app/'
languageCode = 'en-us'
title = "Adisite"
enableEmoji = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'About'
url = '/about'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
